# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ytr < Formula
  desc "Yandex Tracker CLI for humans and LLM agents"
  homepage "https://github.com/slavkluev/ytr"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slavkluev/ytr/releases/download/v0.1.1/ytr_0.1.1_darwin_amd64.tar.gz"
      sha256 "fc415466b7062015395eb5084c8248977b0a56844c4a0a0c5dad54fd82ace08c"

      define_method(:install) do
        bin.install "ytr"
        generate_completions_from_executable(bin/"ytr", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slavkluev/ytr/releases/download/v0.1.1/ytr_0.1.1_darwin_arm64.tar.gz"
      sha256 "bff6e546f20f68b66297866cd6527234a943019ea36de8d9a4c9511f393c815a"

      define_method(:install) do
        bin.install "ytr"
        generate_completions_from_executable(bin/"ytr", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/slavkluev/ytr/releases/download/v0.1.1/ytr_0.1.1_linux_amd64.tar.gz"
      sha256 "348d05ba7a89f38d31d3e710f2893fc91b28f1d240e6f76f98c2641f31c1277e"
      define_method(:install) do
        bin.install "ytr"
        generate_completions_from_executable(bin/"ytr", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slavkluev/ytr/releases/download/v0.1.1/ytr_0.1.1_linux_arm64.tar.gz"
      sha256 "2e4d24580422c25755b3e5c00c8ef83787bbab857bd1bf02a508b684b0bbb8a6"
      define_method(:install) do
        bin.install "ytr"
        generate_completions_from_executable(bin/"ytr", "completion")
      end
    end
  end

  test do
    system "#{bin}/ytr", "version"
  end
end
