# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ytr < Formula
  desc "Yandex Tracker CLI for humans and LLM agents"
  homepage "https://github.com/slavkluev/ytr"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slavkluev/ytr/releases/download/v0.1.0/ytr_0.1.0_darwin_amd64.tar.gz"
      sha256 "5ad708efd0e5a251e771acc1d23f9bd0626146ed54bf1b4e6d052465a1f225ca"

      define_method(:install) do
        bin.install "ytr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slavkluev/ytr/releases/download/v0.1.0/ytr_0.1.0_darwin_arm64.tar.gz"
      sha256 "0a0c71e7266ab06f9b54125469ec8c73be11af930ddc6f62149f083609bdd324"

      define_method(:install) do
        bin.install "ytr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/slavkluev/ytr/releases/download/v0.1.0/ytr_0.1.0_linux_amd64.tar.gz"
      sha256 "454baf8a187681abc173a59798c9eacd380a4e457b77d76641a09d5b8846abf4"
      define_method(:install) do
        bin.install "ytr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slavkluev/ytr/releases/download/v0.1.0/ytr_0.1.0_linux_arm64.tar.gz"
      sha256 "d18f6d34b7ee1f255507aa8aa4ea30219150a2ea67a59daa4dc123fb17ac3ac1"
      define_method(:install) do
        bin.install "ytr"
      end
    end
  end

  test do
    system "#{bin}/ytr", "version"
  end
end
