# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ytr < Formula
  desc "Yandex Tracker CLI for humans and LLM agents"
  homepage "https://github.com/slavkluev/ytr"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slavkluev/ytr/releases/download/v0.1.1/ytr_0.1.1_darwin_amd64.tar.gz"
      sha256 "a016ea3334256eec600b138ec660059b4d6be5305c2ca2ff50ed8d55c012370b"

      define_method(:install) do
        bin.install "ytr"
        generate_completions_from_executable(bin/"ytr", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slavkluev/ytr/releases/download/v0.1.1/ytr_0.1.1_darwin_arm64.tar.gz"
      sha256 "e8da8b06563b748cda7e13d97933cb550c4dab199fa27399d9ac25e5a30c1f4a"

      define_method(:install) do
        bin.install "ytr"
        generate_completions_from_executable(bin/"ytr", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/slavkluev/ytr/releases/download/v0.1.1/ytr_0.1.1_linux_amd64.tar.gz"
      sha256 "32003e3229f6beaf84316dbaf777ea8cd168d3b9d54e6e8ed6968767f00a8e06"
      define_method(:install) do
        bin.install "ytr"
        generate_completions_from_executable(bin/"ytr", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/slavkluev/ytr/releases/download/v0.1.1/ytr_0.1.1_linux_arm64.tar.gz"
      sha256 "30f2d51a436ee2f31a894b8977606df29bb05f96778be14fb34c6f63c82dcdcc"
      define_method(:install) do
        bin.install "ytr"
        generate_completions_from_executable(bin/"ytr", "completion")
      end
    end
  end

  test do
    system "#{bin}/ytr", "version"
  end
end
